Algoritmo "Exibir Mensagem"
// Disciplina   : [Lógica de Programação com Java Script]
// Professor   : Obanma
// Descrição   : Exibir mensagem na telado computador
// Autor(a)    : Kymberly Prates Nascimento
// Data atual  : 29/08/2022
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Kymberly")
Escreval("Prates")
Escreva("Nascimento")

Fimalgoritmo