Algoritmo "Exibir valor de uma variavel"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Exibir o valor de uma variavel
// Autor(a)    : Kymberly Prates Nascimento)
// Data atual  : 29/08/2022
Var
// Seção de Declarações das variáveis 
numero1:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um numero :")
Leia (numero1)
Escreval(numero1)

Fimalgoritmo