Algoritmo "atv manzano com para"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/09/2022
Var
// Seção de Declarações das variáveis 
 quadrado:real
 numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para numero de 15 ate 200 passo 1 faca
 quadrado<- numero^2
 escreval(quadrado)
fimpara

Fimalgoritmo